# Generated by Django 2.2.4 on 2019-09-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='символ')),
                ('description', models.TextField(verbose_name='описание')),
                ('img', models.ImageField(default='default.jpg', upload_to='flags')),
            ],
        ),
    ]
