# Generated by Django 2.2.4 on 2019-09-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flags',
            name='img',
            field=models.CharField(max_length=128, verbose_name='img URL'),
        ),
    ]
